//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventRecorder.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        // ダイアログのサイズを前回終了時の状態で復元するための設定値。
        // マクロの記録データ(XML)とは別に、.NET標準のユーザー設定(%LOCALAPPDATA%配下のuser.config)に
        // 保存する。VSのSettingsデザイナーが使えない環境のため、このファイルは手動で追記している
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("430, 600")]
        public global::System.Drawing.Size WindowSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["WindowSize"]));
            }
            set
            {
                this["WindowSize"] = value;
            }
        }
    }
}
